"""Rebuilt from previous backup

Revision ID: 5d6ed43adb44
Revises: d4867f3a4c0a
Create Date: 2021-11-15 20:07:38.017879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6ed43adb44'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'sign_up_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('account', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.create_index(op.f('ix_account_username'), 'account', ['username'], unique=False)
    op.alter_column('account_data', 'postcode',
               existing_type=sa.CHAR(length=5),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('account_data', 'birthday',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('account_data', 'owner_username',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.Integer(),
               nullable=True)
    op.drop_constraint('account_data_owner_username_key', 'account_data', type_='unique')
    op.create_index(op.f('ix_account_data_id'), 'account_data', ['id'], unique=False)
    op.drop_constraint('account_data_owner_username_fkey', 'account_data', type_='foreignkey')
    op.create_foreign_key(None, 'account_data', 'account', ['owner_username'], ['username'])
    op.alter_column('activity', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('activity', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('activity', 'sport_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('activity', 'organizer',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.create_index(op.f('ix_activity_id'), 'activity', ['id'], unique=False)
    op.drop_constraint('activity_organizer_fkey', 'activity', type_='foreignkey')
    op.create_foreign_key(None, 'activity', 'account', ['organizer'], ['username'])
    op.create_index(op.f('ix_coaching_id'), 'coaching', ['id'], unique=False)
    op.drop_constraint('coaching_coach_fkey', 'coaching', type_='foreignkey')
    op.drop_constraint('coaching_student_fkey', 'coaching', type_='foreignkey')
    op.create_foreign_key(None, 'coaching', 'account', ['coach'], ['username'])
    op.create_foreign_key(None, 'coaching', 'account', ['student'], ['username'])
    op.create_index(op.f('ix_level_id'), 'level', ['id'], unique=False)
    op.alter_column('message', 'send_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.drop_constraint('message_recipient_fkey', 'message', type_='foreignkey')
    op.drop_constraint('message_sender_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'account', ['sender'], ['username'])
    op.create_foreign_key(None, 'message', 'account', ['recipient'], ['username'])
    op.alter_column('offer', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('offer', 'publi_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('offer', 'wear_level_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_offer_id'), 'offer', ['id'], unique=False)
    op.drop_constraint('offer_seller_fkey', 'offer', type_='foreignkey')
    op.create_foreign_key(None, 'offer', 'account', ['seller'], ['username'])
    op.drop_constraint('participation_participant_fkey', 'participation', type_='foreignkey')
    op.create_foreign_key(None, 'participation', 'account', ['participant'], ['username'])
    op.alter_column('review', 'critic_username',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    op.drop_constraint('review_username_fkey', 'review', type_='foreignkey')
    op.drop_constraint('review_critic_username_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'account', ['username'], ['username'])
    op.create_foreign_key(None, 'review', 'account', ['critic_username'], ['username'])
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_role_name'), 'role', ['role_name'], unique=True)
    op.create_index(op.f('ix_sport_id'), 'sport', ['id'], unique=False)
    op.create_index(op.f('ix_wear_id'), 'wear', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wear_id'), table_name='wear')
    op.drop_index(op.f('ix_sport_id'), table_name='sport')
    op.drop_index(op.f('ix_role_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_critic_username_fkey', 'review', 'account', ['critic_username'], ['username'], onupdate='CASCADE')
    op.create_foreign_key('review_username_fkey', 'review', 'account', ['username'], ['username'], onupdate='CASCADE')
    op.drop_index(op.f('ix_review_id'), table_name='review')
    op.alter_column('review', 'critic_username',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.drop_constraint(None, 'participation', type_='foreignkey')
    op.create_foreign_key('participation_participant_fkey', 'participation', 'account', ['participant'], ['username'], onupdate='CASCADE')
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.create_foreign_key('offer_seller_fkey', 'offer', 'account', ['seller'], ['username'], onupdate='CASCADE')
    op.drop_index(op.f('ix_offer_id'), table_name='offer')
    op.alter_column('offer', 'wear_level_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('offer', 'publi_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('offer', 'price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_sender_fkey', 'message', 'account', ['sender'], ['username'], onupdate='CASCADE')
    op.create_foreign_key('message_recipient_fkey', 'message', 'account', ['recipient'], ['username'], onupdate='CASCADE')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.alter_column('message', 'send_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_index(op.f('ix_level_id'), table_name='level')
    op.drop_constraint(None, 'coaching', type_='foreignkey')
    op.drop_constraint(None, 'coaching', type_='foreignkey')
    op.create_foreign_key('coaching_student_fkey', 'coaching', 'account', ['student'], ['username'], onupdate='CASCADE')
    op.create_foreign_key('coaching_coach_fkey', 'coaching', 'account', ['coach'], ['username'], onupdate='CASCADE')
    op.drop_index(op.f('ix_coaching_id'), table_name='coaching')
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.create_foreign_key('activity_organizer_fkey', 'activity', 'account', ['organizer'], ['username'], onupdate='CASCADE')
    op.drop_index(op.f('ix_activity_id'), table_name='activity')
    op.alter_column('activity', 'organizer',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('activity', 'sport_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('activity', 'end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('activity', 'start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_constraint(None, 'account_data', type_='foreignkey')
    op.create_foreign_key('account_data_owner_username_fkey', 'account_data', 'account', ['owner_username'], ['username'], onupdate='CASCADE')
    op.drop_index(op.f('ix_account_data_id'), table_name='account_data')
    op.create_unique_constraint('account_data_owner_username_key', 'account_data', ['owner_username'])
    op.alter_column('account_data', 'owner_username',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('account_data', 'birthday',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('account_data', 'postcode',
               existing_type=sa.String(),
               type_=sa.CHAR(length=5),
               existing_nullable=False)
    op.drop_index(op.f('ix_account_username'), table_name='account')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.alter_column('account', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('account', 'sign_up_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
